src/nbsap/forms.py, src/nbsap/templates/eu_indicators/map_eu_indicator.html
I've create CRUD oeprations as well as Mapping with Eu Targets and Aichi Targets
=> Administration indicators

src/nbsap/forms.py
Steps to reproduce:
- open EU Indicator mapping form
- remove all most relevant EU/AICHI targets
- save the updates
=> Fix crash in the EU Indicator mapping form

src/nbsap/forms.py, src/nbsap/models.py, src/nbsap/templates/manager/activities/edit_eu_strategy_activity.html, src/nbsap/views/activities.py
=> Activity code

src/nbsap/forms.py, src/nbsap/models.py, src/nbsap/templates/_bits/nav_menu.html, src/nbsap/templates/manager/admin_nav_tabs.html, src/nbsap/templates/manager/nat_indicators/add_nat_indicator.html, src/nbsap/templates/manager/nat_indicators/edit_nat_indicator.html, src/nbsap/templates/manager/nat_indicators/list_nat_indicators.html, src/nbsap/templates/manager/nat_indicators/map_nat_indicator.html, src/nbsap/templates/manager/nat_indicators/view_nat_indicator.html, src/nbsap/templates/nat_strategy/nat_indicators.html, src/nbsap/tests/__init__.py, src/nbsap/tests/factories.py, src/nbsap/tests/nat_indicators.py, src/nbsap/urls.py, src/nbsap/utils.py, src/nbsap/views/__init__.py, src/nbsap/views/nat_indicators.py
=> Add National indicators feature, refs: #17023

src/nbsap/fixtures/eu_aichi_indicators_mapping.json, src/nbsap/fixtures/eu_indicators.json, src/nbsap/forms.py, src/nbsap/models.py, src/nbsap/templates/eu_strategy/eu_indicators.html, src/nbsap/templates/eu_strategy/eu_targets.html, src/nbsap/templates/manager/eu_indicators/add_eu_indicator.html, src/nbsap/templates/manager/eu_indicators/edit_eu_indicator.html, src/nbsap/templates/manager/eu_indicators/eu_indicator_form.html, src/nbsap/templates/manager/eu_indicators/list_eu_indicators.html, src/nbsap/templates/manager/eu_indicators/map_eu_indicator.html, src/nbsap/templates/manager/eu_indicators/view_eu_indicator.html, src/nbsap/templates/manager/eu_strategy/mapping/add_eu_aichi_strategy.html, src/nbsap/templates/manager/eu_strategy/mapping/edit_eu_aichi_strategy.html, src/nbsap/views/indicators.py, src/nbsap/views/nat_indicators.py
=> Refactor eu indicators

src/nbsap/templates/nat_strategy/implementation.html, src/nbsap/templates/objectives/nat_strategy.html
=> [subobjectives_links] Add subobjectives links and backlinks. Refs #24851

src/nbsap/views/objectives.py
=> [nat_strategy_dw] Update the national strategy download xlsx

src/nbsap/templates/manager/eu_strategy/mapping/list_eu_aichi_strategy.html
=> [eu_aichi_mapping] Update the aichi mapping view. Refs #25182

src/nbsap/forms.py, src/nbsap/models.py, src/nbsap/templates/manager/nat_indicators/edit_nat_indicator.html, src/nbsap/templates/manager/nat_indicators/list_nat_indicators.html, src/nbsap/templates/manager/nat_indicators/view_nat_indicator.html
=> [nat_subindicators] Clean hierarchical structure in the national indicators

src/nbsap/templates/manager/nat_strategy/mapping/nat_strategy_aichi_mapping.html, src/nbsap/templates/nat_strategy/nat_indicators.html
=> [objective_nat_indicators] Show national indicators in the national strategy

instance/local_settings.py.example, src/nbsap/models.py
=> [reg_indicators] Add regional national indicators. Refs #25794

src/nbsap/models.py, src/nbsap/templates/manager/eu_strategy/mapping/list_eu_aichi_strategy.html
=> [aichi_mapping_view] Remove the Eu Inidicator title from listing

src/nbsap/forms.py, src/nbsap/templates/manager/nat_indicators/list_nat_indicators.html
=> National indicators admin view

src/nbsap/management/commands/import_nat.py, src/nbsap/templates/objectives/nat_strategy.html, src/nbsap/tests/nat_indicators.py, src/nbsap/tests/objectives.py
=> Import feature

src/nbsap/views/indicators.py, src/nbsap/views/nat_indicators.py
=> [indicators_ordering] Order indicators by type. Refs #25981

src/nbsap/forms.py, src/nbsap/models.py, src/nbsap/settings.py, src/nbsap/templates/manager/nat_indicators/add_nat_indicator.html, src/nbsap/templates/manager/nat_indicators/edit_nat_indicator.html, src/nbsap/templates/manager/nat_indicators/list_nat_indicators.html, src/nbsap/templates/manager/nat_indicators/view_nat_indicator.html, src/nbsap/templates/nat_strategy/nat_indicators.html, src/nbsap/tests/factories.py, src/nbsap/tests/nat_indicators.py, src/nbsap/views/nat_indicators.py
=> National indicator type

src/nbsap/management/commands/import_nat.py
PR for #26677.
@alexef please review and merge
=> Differentiate objectives and subobjectives at import

src/nbsap/forms.py, src/nbsap/models.py, src/nbsap/templates/manager/eu_strategy/view_eu_strategy_target.html
PR for #24207
@alexef please review
=> Clean subactions listing

src/nbsap/forms.py, src/nbsap/management/commands/export_nat.py, src/nbsap/models.py, src/nbsap/templates/aichi/goals.html, src/nbsap/templates/manager/nat_strategy/mapping/add_national_strategy.html, src/nbsap/templates/manager/nat_strategy/mapping/edit_national_strategy.html, src/nbsap/templates/manager/nat_strategy/mapping/list_national_strategy.html, src/nbsap/templates/manager/nat_strategy/mapping/nat_action_aichi_mapping.html, src/nbsap/templatetags/utils.py, src/nbsap/test_settings.py, src/nbsap/tests/factories.py, src/nbsap/tests/national_strategy.py, src/nbsap/views/objectives.py
Allow for multiple most relevant Aichi Targets. Refs: #26677
@anaion please review.
Not adding a migration since it's hard to define one that will work on all the different language configurations we have on nbsap instances.
=> Most relevant m2m

Dockerfile, instance/local_settings.py.example, src/nbsap/fixtures/aichi_goals.json, src/nbsap/fixtures/aichi_targets.json, src/nbsap/fixtures/eu_actions.json, src/nbsap/fixtures/eu_indicators.json, src/nbsap/fixtures/eu_targets.json, src/nbsap/fixtures/pages.json, src/nbsap/models.py, src/nbsap/settings.py, src/nbsap/tests/base.py, src/nbsap/tests/factories.py, src/nbsap/tests/nat_indicators.py, src/nbsap/tests/national_actions.py, src/nbsap/tests/national_strategy.py, src/nbsap/tests/objectives.py, src/nbsap/tests/subobjectives.py
=> Language code

tct/models.py
=> Fix export bug

tct/tests/objectives.py, tct/views/objectives.py
The problem is that the object 'strategy.objective' might not contain the attribute 'description_lang', so I passed a default value to getattr() function.
=> Fix download xslx
